const prompts = [
  {
    id: 1,
    title: "Line Graph: Internet Users",
    chartType: "line",
    difficulty: "medium",
    topic: "technology",
    tags: ["internet", "growth", "countries"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The line graph below shows the number of internet users per 100 inhabitants in three countries from 2000 to 2020.",
    data: [
      { year: "2000", USA: 43, Japan: 30, India: 0.5 },
      { year: "2004", USA: 65, Japan: 62, India: 2 },
      { year: "2008", USA: 74, Japan: 75, India: 4 },
      { year: "2012", USA: 81, Japan: 79, India: 12 },
      { year: "2016", USA: 87, Japan: 84, India: 30 },
      { year: "2020", USA: 91, Japan: 90, India: 50 },
    ],
    lines: [
      { dataKey: "USA", color: "#4f46e5" },
      { dataKey: "Japan", color: "#dc2626" },
      { dataKey: "India", color: "#16a34a" },
    ],
    xAxisKey: "year",
    yAxisLabel: "Users per 100 inhabitants",
  },
  {
    id: 2,
    title: "Bar Chart: Energy Sources",
    chartType: "bar",
    difficulty: "medium",
    topic: "environment",
    tags: ["energy", "renewable", "comparison"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The bar chart below shows the percentage of energy generated from different sources in a European country in 2005 and 2025.",
    data: [
      { source: "Coal", 2005: 45, 2025: 20 },
      { source: "Natural Gas", 2005: 30, 2025: 25 },
      { source: "Nuclear", 2005: 18, 2025: 22 },
      { source: "Renewable", 2005: 7, 2025: 33 },
    ],
    bars: [
      { dataKey: "2005", color: "#f97316", name: "2005" },
      { dataKey: "2025", color: "#22c55e", name: "2025" },
    ],
    xAxisKey: "source",
    yAxisLabel: "Percentage (%)",
  },
  {
    id: 3,
    title: "Pie Charts: Household Spending",
    chartType: "pie",
    difficulty: "medium",
    topic: "economy",
    tags: ["spending", "household", "budget"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The pie charts below show the average household spending in four categories as a percentage of total spending in two different years: 2010 and 2020.",
    pieData: [
      {
        year: "2010",
        data: [
          { name: "Housing", value: 35, color: "#4f46e5" },
          { name: "Food", value: 28, color: "#f97316" },
          { name: "Transport", value: 22, color: "#22c55e" },
          { name: "Entertainment", value: 15, color: "#eab308" },
        ],
      },
      {
        year: "2020",
        data: [
          { name: "Housing", value: 38, color: "#4f46e5" },
          { name: "Food", value: 20, color: "#f97316" },
          { name: "Transport", value: 18, color: "#22c55e" },
          { name: "Entertainment", value: 24, color: "#eab308" },
        ],
      },
    ],
  },
  {
    id: 4,
    title: "Table: International Student Enrolment",
    chartType: "table",
    difficulty: "hard",
    topic: "society",
    tags: ["education", "students", "international"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The table below shows the number of international students (in thousands) enrolled in universities in four English-speaking countries from 2015 to 2023.",
    tableData: [
      {
        country: "United Kingdom",
        2015: 428,
        2017: 442,
        2019: 485,
        2021: 520,
        2023: 558,
      },
      {
        country: "United States",
        2015: 907,
        2017: 890,
        2019: 860,
        2021: 835,
        2023: 810,
      },
      {
        country: "Canada",
        2015: 235,
        2017: 285,
        2019: 345,
        2021: 420,
        2023: 480,
      },
      {
        country: "Australia",
        2015: 310,
        2017: 365,
        2019: 420,
        2021: 390,
        2023: 450,
      },
    ],
  },
  {
    id: 5,
    title: "Process Diagram: Water Cycle",
    chartType: "process",
    difficulty: "easy",
    topic: "environment",
    tags: ["water", "cycle", "natural"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The diagram below shows the water cycle, which is the continuous movement of water within the Earth and its atmosphere.",
    stages: [
      {
        id: 1,
        label: "Evaporation",
        desc: "Sun heats water in oceans, rivers, and lakes, turning it into water vapour that rises into the air.",
        x: 20,
        y: 55,
      },
      {
        id: 2,
        label: "Condensation",
        desc: "Water vapour rises, cools down, and forms clouds.",
        x: 50,
        y: 15,
      },
      {
        id: 3,
        label: "Precipitation",
        desc: "Water falls back to Earth as rain, snow, or hail.",
        x: 80,
        y: 55,
      },
      {
        id: 4,
        label: "Collection",
        desc: "Water collects in oceans, rivers, and lakes, and the cycle begins again.",
        x: 50,
        y: 85,
      },
    ],
  },
  // --- Line Graphs (IDs 6-10) ---
  {
    id: 6,
    title: "Line Graph: Urban vs Rural Population",
    chartType: "line",
    difficulty: "medium",
    topic: "society",
    tags: ["urbanisation", "population", "countries"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The line graph below shows the percentage of urban population in three countries from 1970 to 2020.",
    data: [
      { year: "1970", Brazil: 55.9, China: 17.4, Nigeria: 17.8 },
      { year: "1980", Brazil: 65.5, China: 19.4, Nigeria: 22.0 },
      { year: "1990", Brazil: 73.9, China: 26.4, Nigeria: 29.7 },
      { year: "2000", Brazil: 81.2, China: 35.9, Nigeria: 34.8 },
      { year: "2010", Brazil: 84.3, China: 49.2, Nigeria: 42.3 },
      { year: "2020", Brazil: 87.1, China: 63.9, Nigeria: 52.0 },
    ],
    lines: [
      { dataKey: "Brazil", color: "#4f46e5" },
      { dataKey: "China", color: "#dc2626" },
      { dataKey: "Nigeria", color: "#16a34a" },
    ],
    xAxisKey: "year",
    yAxisLabel: "Urban population (%)",
  },
  {
    id: 7,
    title: "Line Graph: Average Monthly Temperature",
    chartType: "line",
    difficulty: "easy",
    topic: "environment",
    tags: ["temperature", "climate", "cities"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The line graph below shows the average monthly temperature (°C) in four cities over a year.",
    data: [
      { month: "Jan", London: 5.2, Sydney: 26.5, Tokyo: 5.8, Cairo: 14.0 },
      { month: "Mar", London: 8.3, Sydney: 24.8, Tokyo: 10.6, Cairo: 18.4 },
      { month: "May", London: 14.1, Sydney: 18.5, Tokyo: 19.8, Cairo: 27.2 },
      { month: "Jul", London: 19.4, Sydney: 13.2, Tokyo: 27.3, Cairo: 33.1 },
      { month: "Sep", London: 16.2, Sydney: 17.8, Tokyo: 24.1, Cairo: 29.5 },
      { month: "Nov", London: 8.8, Sydney: 22.3, Tokyo: 13.2, Cairo: 19.8 },
    ],
    lines: [
      { dataKey: "London", color: "#4f46e5" },
      { dataKey: "Sydney", color: "#f97316" },
      { dataKey: "Tokyo", color: "#dc2626" },
      { dataKey: "Cairo", color: "#eab308" },
    ],
    xAxisKey: "month",
    yAxisLabel: "Temperature (°C)",
  },
  {
    id: 8,
    title: "Line Graph: Company Revenue Trends",
    chartType: "line",
    difficulty: "medium",
    topic: "economy",
    tags: ["revenue", "business", "growth"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The line graph below shows the annual revenue (in billion USD) of three technology companies from 2018 to 2023.",
    data: [
      { year: "2018", "Company A": 52.3, "Company B": 38.7, "Company C": 21.5 },
      { year: "2019", "Company A": 58.1, "Company B": 42.4, "Company C": 26.8 },
      { year: "2020", "Company A": 67.4, "Company B": 39.8, "Company C": 34.2 },
      { year: "2021", "Company A": 81.2, "Company B": 48.5, "Company C": 45.6 },
      { year: "2022", "Company A": 79.6, "Company B": 55.1, "Company C": 52.3 },
      { year: "2023", "Company A": 88.3, "Company B": 61.7, "Company C": 58.9 },
    ],
    lines: [
      { dataKey: "Company A", color: "#4f46e5" },
      { dataKey: "Company B", color: "#dc2626" },
      { dataKey: "Company C", color: "#16a34a" },
    ],
    xAxisKey: "year",
    yAxisLabel: "Revenue (billion USD)",
  },
  {
    id: 9,
    title: "Line Graph: Employment Rate by Sector",
    chartType: "line",
    difficulty: "hard",
    topic: "economy",
    tags: ["employment", "sectors", "trends"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The line graph below shows the percentage of the workforce employed in three sectors in a developing country from 1990 to 2020.",
    data: [
      { year: "1990", Agriculture: 62.4, Industry: 15.8, Services: 21.8 },
      { year: "1995", Agriculture: 55.1, Industry: 19.3, Services: 25.6 },
      { year: "2000", Agriculture: 46.3, Industry: 22.7, Services: 31.0 },
      { year: "2005", Agriculture: 38.5, Industry: 25.1, Services: 36.4 },
      { year: "2010", Agriculture: 30.2, Industry: 26.8, Services: 43.0 },
      { year: "2015", Agriculture: 24.7, Industry: 25.4, Services: 49.9 },
      { year: "2020", Agriculture: 19.3, Industry: 23.6, Services: 57.1 },
    ],
    lines: [
      { dataKey: "Agriculture", color: "#16a34a" },
      { dataKey: "Industry", color: "#f97316" },
      { dataKey: "Services", color: "#4f46e5" },
    ],
    xAxisKey: "year",
    yAxisLabel: "Workforce (%)",
  },
  {
    id: 10,
    title: "Line Graph: Renewable Energy Consumption",
    chartType: "line",
    difficulty: "medium",
    topic: "environment",
    tags: ["renewable", "energy", "solar", "wind"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The line graph below shows the consumption of renewable energy from three sources (in exajoules) globally from 2010 to 2025.",
    data: [
      { year: "2010", Solar: 0.2, Wind: 1.5, Hydro: 12.3 },
      { year: "2013", Solar: 0.7, Wind: 2.8, Hydro: 13.1 },
      { year: "2016", Solar: 1.8, Wind: 4.3, Hydro: 13.8 },
      { year: "2019", Solar: 3.5, Wind: 6.1, Hydro: 14.2 },
      { year: "2022", Solar: 5.8, Wind: 8.4, Hydro: 14.9 },
      { year: "2025", Solar: 9.2, Wind: 11.6, Hydro: 15.4 },
    ],
    lines: [
      { dataKey: "Solar", color: "#eab308" },
      { dataKey: "Wind", color: "#4f46e5" },
      { dataKey: "Hydro", color: "#06b6d4" },
    ],
    xAxisKey: "year",
    yAxisLabel: "Consumption (exajoules)",
  },
  // --- Bar Charts (IDs 11-15) ---
  {
    id: 11,
    title: "Bar Chart: Education Levels by Gender",
    chartType: "bar",
    difficulty: "easy",
    topic: "society",
    tags: ["education", "gender", "levels"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The bar chart below shows the percentage of males and females who completed primary, secondary, and tertiary education in a developing country in 2022.",
    data: [
      { level: "Primary", Male: 92.4, Female: 88.7 },
      { level: "Secondary", Male: 71.3, Female: 64.8 },
      { level: "Tertiary", Male: 28.5, Female: 34.2 },
    ],
    bars: [
      { dataKey: "Male", color: "#4f46e5", name: "Male" },
      { dataKey: "Female", color: "#ec4899", name: "Female" },
    ],
    xAxisKey: "level",
    yAxisLabel: "Percentage (%)",
  },
  {
    id: 12,
    title: "Bar Chart: International Tourist Arrivals",
    chartType: "bar",
    difficulty: "medium",
    topic: "economy",
    tags: ["tourism", "countries", "comparison"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The bar chart below shows the number of international tourist arrivals (in millions) in six countries in 2019 and 2023.",
    data: [
      { country: "France", 2019: 90.2, 2023: 82.5 },
      { country: "Spain", 2019: 83.5, 2023: 78.3 },
      { country: "USA", 2019: 79.3, 2023: 71.6 },
      { country: "China", 2019: 65.7, 2023: 42.8 },
      { country: "Italy", 2019: 64.5, 2023: 61.2 },
      { country: "Thailand", 2019: 39.8, 2023: 28.1 },
    ],
    bars: [
      { dataKey: "2019", color: "#4f46e5", name: "2019" },
      { dataKey: "2023", color: "#f97316", name: "2023" },
    ],
    xAxisKey: "country",
    yAxisLabel: "Arrivals (millions)",
  },
  {
    id: 13,
    title: "Bar Chart: Daily Calorie Intake by Food Group",
    chartType: "bar",
    difficulty: "medium",
    topic: "health",
    tags: ["nutrition", "diet", "food"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The bar chart below shows the average daily calorie intake (in kcal) from five food groups in three countries.",
    data: [
      { group: "Grains", Japan: 680, USA: 520, India: 810 },
      { group: "Meat & Fish", Japan: 310, USA: 580, India: 145 },
      { group: "Dairy", Japan: 165, USA: 340, India: 210 },
      { group: "Fruits & Veg", Japan: 220, USA: 175, India: 195 },
      { group: "Fats & Oils", Japan: 125, USA: 385, India: 240 },
    ],
    bars: [
      { dataKey: "Japan", color: "#dc2626", name: "Japan" },
      { dataKey: "USA", color: "#4f46e5", name: "USA" },
      { dataKey: "India", color: "#16a34a", name: "India" },
    ],
    xAxisKey: "group",
    yAxisLabel: "Calories (kcal)",
  },
  {
    id: 14,
    title: "Bar Chart: Transport Mode to Work",
    chartType: "bar",
    difficulty: "easy",
    topic: "society",
    tags: ["transport", "commuting", "cities"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The bar chart below shows the percentage of workers using different transport modes to commute in two cities.",
    data: [
      { mode: "Car", "City A": 62.5, "City B": 34.8 },
      { mode: "Bus", "City A": 15.3, "City B": 28.2 },
      { mode: "Bicycle", "City A": 4.2, "City B": 18.5 },
      { mode: "Walk", "City A": 8.7, "City B": 12.3 },
      { mode: "Train", "City A": 9.3, "City B": 6.2 },
    ],
    bars: [
      { dataKey: "City A", color: "#4f46e5", name: "City A" },
      { dataKey: "City B", color: "#16a34a", name: "City B" },
    ],
    xAxisKey: "mode",
    yAxisLabel: "Percentage (%)",
  },
  {
    id: 15,
    title: "Bar Chart: Types of Housing",
    chartType: "bar",
    difficulty: "hard",
    topic: "society",
    tags: ["housing", "accommodation", "cities"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The bar chart below shows the percentage of people living in different types of housing in four major cities.",
    data: [
      {
        type: "Apartment",
        London: 52.3,
        Tokyo: 71.8,
        Sydney: 38.4,
        "New York": 68.5,
      },
      {
        type: "House",
        London: 34.1,
        Tokyo: 18.2,
        Sydney: 48.7,
        "New York": 14.3,
      },
      {
        type: "Studio",
        London: 13.6,
        Tokyo: 10.0,
        Sydney: 12.9,
        "New York": 17.2,
      },
    ],
    bars: [
      { dataKey: "London", color: "#4f46e5", name: "London" },
      { dataKey: "Tokyo", color: "#dc2626", name: "Tokyo" },
      { dataKey: "Sydney", color: "#16a34a", name: "Sydney" },
      { dataKey: "New York", color: "#f97316", name: "New York" },
    ],
    xAxisKey: "type",
    yAxisLabel: "Percentage (%)",
  },
  // --- Pie Charts (IDs 16-18) ---
  {
    id: 16,
    title: "Pie Charts: Government Budget Allocation",
    chartType: "pie",
    difficulty: "medium",
    topic: "economy",
    tags: ["government", "budget", "spending"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The pie charts below show the government budget allocation by sector as a percentage of total government spending in a country in 2015 and 2023.",
    pieData: [
      {
        year: "2015",
        data: [
          { name: "Education", value: 22, color: "#4f46e5" },
          { name: "Healthcare", value: 18, color: "#dc2626" },
          { name: "Defence", value: 24, color: "#6b7280" },
          { name: "Infrastructure", value: 16, color: "#f97316" },
          { name: "Social Welfare", value: 12, color: "#16a34a" },
          { name: "Other", value: 8, color: "#eab308" },
        ],
      },
      {
        year: "2023",
        data: [
          { name: "Education", value: 26, color: "#4f46e5" },
          { name: "Healthcare", value: 23, color: "#dc2626" },
          { name: "Defence", value: 17, color: "#6b7280" },
          { name: "Infrastructure", value: 14, color: "#f97316" },
          { name: "Social Welfare", value: 14, color: "#16a34a" },
          { name: "Other", value: 6, color: "#eab308" },
        ],
      },
    ],
  },
  {
    id: 17,
    title: "Pie Charts: Smartphone Market Share",
    chartType: "pie",
    difficulty: "easy",
    topic: "technology",
    tags: ["smartphones", "market", "brands"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The pie charts below show the global smartphone market share (in percent) by brand in 2019 and 2023.",
    pieData: [
      {
        year: "2019",
        data: [
          { name: "Samsung", value: 31, color: "#4f46e5" },
          { name: "Apple", value: 24, color: "#6b7280" },
          { name: "Huawei", value: 17, color: "#dc2626" },
          { name: "Xiaomi", value: 9, color: "#f97316" },
          { name: "Others", value: 19, color: "#16a34a" },
        ],
      },
      {
        year: "2023",
        data: [
          { name: "Samsung", value: 27, color: "#4f46e5" },
          { name: "Apple", value: 28, color: "#6b7280" },
          { name: "Huawei", value: 5, color: "#dc2626" },
          { name: "Xiaomi", value: 14, color: "#f97316" },
          { name: "Others", value: 26, color: "#16a34a" },
        ],
      },
    ],
  },
  {
    id: 18,
    title: "Pie Charts: How Students Spend Their Day",
    chartType: "pie",
    difficulty: "medium",
    topic: "society",
    tags: ["students", "time", "activities"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The pie charts below show how university students typically spend their time on a weekday and at the weekend (hours per day).",
    pieData: [
      {
        year: "Weekday",
        data: [
          { name: "Studying", value: 29, color: "#4f46e5" },
          { name: "Sleeping", value: 29, color: "#6b7280" },
          { name: "Socialising", value: 10, color: "#f97316" },
          { name: "Exercise", value: 6, color: "#16a34a" },
          { name: "Part-time Work", value: 13, color: "#dc2626" },
          { name: "Other", value: 13, color: "#eab308" },
        ],
      },
      {
        year: "Weekend",
        data: [
          { name: "Studying", value: 13, color: "#4f46e5" },
          { name: "Sleeping", value: 33, color: "#6b7280" },
          { name: "Socialising", value: 21, color: "#f97316" },
          { name: "Exercise", value: 10, color: "#16a34a" },
          { name: "Part-time Work", value: 10, color: "#dc2626" },
          { name: "Other", value: 13, color: "#eab308" },
        ],
      },
    ],
  },
  // --- Tables (IDs 19-21) ---
  {
    id: 19,
    title: "Table: Economic Indicators",
    chartType: "table",
    difficulty: "hard",
    topic: "economy",
    tags: ["GDP", "inflation", "unemployment"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The table below shows three economic indicators (GDP growth %, inflation rate %, and unemployment rate %) for five countries in 2023.",
    tableData: [
      {
        country: "USA",
        "GDP Growth (%)": 2.5,
        "Inflation (%)": 3.4,
        "Unemployment (%)": 3.7,
      },
      {
        country: "Germany",
        "GDP Growth (%)": -0.3,
        "Inflation (%)": 5.9,
        "Unemployment (%)": 5.7,
      },
      {
        country: "Japan",
        "GDP Growth (%)": 1.9,
        "Inflation (%)": 3.2,
        "Unemployment (%)": 2.6,
      },
      {
        country: "Brazil",
        "GDP Growth (%)": 2.9,
        "Inflation (%)": 4.6,
        "Unemployment (%)": 7.8,
      },
      {
        country: "India",
        "GDP Growth (%)": 7.2,
        "Inflation (%)": 5.4,
        "Unemployment (%)": 7.1,
      },
    ],
  },
  {
    id: 20,
    title: "Table: Sports Participation Rates",
    chartType: "table",
    difficulty: "medium",
    topic: "health",
    tags: ["sports", "participation", "gender"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The table below shows the percentage of adults who participate in six sports at least once a week, broken down by gender.",
    tableData: [
      { sport: "Swimming", Male: 14.2, Female: 18.5, Total: 16.3 },
      { sport: "Running", Male: 22.8, Female: 16.4, Total: 19.6 },
      { sport: "Cycling", Male: 18.3, Female: 9.7, Total: 14.0 },
      { sport: "Football", Male: 24.5, Female: 3.8, Total: 14.2 },
      { sport: "Yoga", Male: 4.6, Female: 19.2, Total: 11.9 },
      { sport: "Tennis", Male: 8.1, Female: 6.3, Total: 7.2 },
    ],
  },
  {
    id: 21,
    title: "Table: Internet Usage by Age Group",
    chartType: "table",
    difficulty: "medium",
    topic: "technology",
    tags: ["internet", "age", "activities"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The table below shows the percentage of people in different age groups who use the internet for four activities.",
    tableData: [
      {
        "Age Group": "16-24",
        "Social Media": 94.2,
        Shopping: 78.5,
        News: 52.3,
        "Online Banking": 61.8,
      },
      {
        "Age Group": "25-34",
        "Social Media": 88.7,
        Shopping: 82.1,
        News: 64.5,
        "Online Banking": 79.3,
      },
      {
        "Age Group": "35-49",
        "Social Media": 72.4,
        Shopping: 76.8,
        News: 71.2,
        "Online Banking": 82.6,
      },
      {
        "Age Group": "50-64",
        "Social Media": 51.3,
        Shopping: 58.4,
        News: 73.8,
        "Online Banking": 68.9,
      },
      {
        "Age Group": "65+",
        "Social Media": 28.6,
        Shopping: 32.1,
        News: 65.4,
        "Online Banking": 41.2,
      },
    ],
  },
  // --- Process Diagrams (IDs 22-23) ---
  {
    id: 22,
    title: "Process Diagram: Chocolate Production",
    chartType: "process",
    difficulty: "medium",
    topic: "economy",
    tags: ["chocolate", "manufacturing", "production"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The diagram below shows the stages involved in the production of chocolate from cacao beans.",
    stages: [
      {
        id: 1,
        label: "Harvesting",
        desc: "Ripe cacao pods are harvested from trees and the beans are removed from the pods.",
        x: 10,
        y: 50,
      },
      {
        id: 2,
        label: "Fermenting",
        desc: "Beans are placed in containers and left to ferment for 5-7 days to develop flavour.",
        x: 28,
        y: 25,
      },
      {
        id: 3,
        label: "Drying",
        desc: "Fermented beans are spread out and dried in the sun for approximately one week.",
        x: 46,
        y: 50,
      },
      {
        id: 4,
        label: "Roasting",
        desc: "Dried beans are roasted at 120-150°C to bring out the chocolate aroma.",
        x: 64,
        y: 25,
      },
      {
        id: 5,
        label: "Grinding",
        desc: "Roasted beans are cracked and ground into a liquid paste called chocolate liquor.",
        x: 82,
        y: 50,
      },
      {
        id: 6,
        label: "Moulding",
        desc: "The refined chocolate is poured into moulds, cooled, and packaged for distribution.",
        x: 90,
        y: 80,
      },
    ],
  },
  {
    id: 23,
    title: "Process Diagram: Plastic Recycling",
    chartType: "process",
    difficulty: "easy",
    topic: "environment",
    tags: ["recycling", "plastic", "waste"],
    task: "Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
    description:
      "The diagram below shows the process of recycling plastic waste into new products.",
    stages: [
      {
        id: 1,
        label: "Collection",
        desc: "Plastic waste is collected from households and businesses through recycling bins and collection services.",
        x: 10,
        y: 50,
      },
      {
        id: 2,
        label: "Sorting",
        desc: "Collected plastics are sorted by type (PET, HDPE, etc.) using automated machines and manual inspection.",
        x: 30,
        y: 25,
      },
      {
        id: 3,
        label: "Cleaning",
        desc: "Sorted plastics are washed to remove labels, adhesives, and food residue.",
        x: 50,
        y: 50,
      },
      {
        id: 4,
        label: "Shredding",
        desc: "Clean plastics are shredded into small flakes and melted into pellets.",
        x: 70,
        y: 25,
      },
      {
        id: 5,
        label: "Manufacturing",
        desc: "Pellets are used as raw material to manufacture new plastic products such as bottles and containers.",
        x: 90,
        y: 50,
      },
    ],
  },
];

export default prompts;
